#https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
server:
  protocal: http://
  domain: localhost
  port: 8082
  tomcat:
    max-swallow-size: -1  #https://stackoverflow.com/questions/2689989/how-to-handle-maxuploadsizeexceededexception
    remoteip:
      remote-ip-header: "x-forwarded-for"
      protocol-header: "x-forwarded-proto"
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 1440m
      cookie:
        name: MOWEBJSESSIONID



spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 256MB
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML
    encoding: UTF-8
    view-names: thymeleaf/*
    template-resolver-order: 0
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    default:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://3.38.10.39:3306/dure?allowMultiQueries=true
      username: dure
      password: enfp1!2@
      maximum-pool-size: 3


jasypt:
  encryptor:
    bean: encryptorBean

apps:
  api-request-mapping: /api/v1
  packages: com.hmsec
  host: http://localhost:${server.port}
  error:
    page: thymeleaf/error
  upload:
    # s3, ftp, sftp, file
    fileSystem: file
    allowedUploadExtensions: jpg,jpeg,png,gif,mp4,pdf
    allowedAccessExtensions: jpg,jpeg,png,gif,mp4,pdf
    publicUrl: /data/files
    root: ${apps.upload.fileSystem}:///home/appdev/webapps/
    #root: ${apps.upload.fileSystem}://${aws.accessKey}:${aws.secretKey}:${aws.region}@${aws.bucket}.s3.amazonaws.com
  product:
    thumbnailSize:
      width: 500
      height: 500